export const REQUEST_INIT = 'REQUEST_INIT';
export const FETCH_PUBLISHERS_DATA_RESPONSE = 'FETCH_PUBLISHERS_DATA_RESPONSE';
export const ADD_PUBLISHER_RESPONSE = 'ADD_PUBLISHER_RESPONSE';
export const REMOVE_PUBLISHER_RESPONSE = 'REMOVE_PUBLISHER_RESPONSE';
export const UPDATE_PUBLISHER_RESPONSE = 'UPDATE_PUBLISHER_RESPONSE';
