export const REQUEST_INIT = 'REQUEST_INIT';
export const FETCH_DATA_SUBJECTS_RESPONSE = 'FETCH_DATA_SUBJECTS_RESPONSE';
export const FETCH_ALL_SUBJECTS_RESPONSE = 'FETCH_ALL_SUBJECTS_RESPONSE';
export const FETCH_ALL_CLASSES_RESPONSE = 'FETCH_ALL_CLASSES_RESPONSE';
export const ADD_SUBJECT_RESPONSE = 'ADD_SUBJECT_RESPONSE';
export const UPDATE_SUBJECT_RESPONSE = 'UPDATE_SUBJECT_RESPONSE';
export const REMOVE_SUBJECT_RESPONSE = 'REMOVE_SUBJECT_RESPONSE';
