export const REQUEST_INIT = 'REQUEST_INIT';

export const FETCH_QUESTION_TYPES_RESPONSE = 'FETCH_QUESTION_TYPES_RESPONSE';
export const FETCH_QUESTION_TYPES_RESPONSE2 = 'FETCH_QUESTION_TYPES_RESPONSE2';
export const FETCH_QUESTIONS_RESPONSE = 'FETCH_QUESTIONS_RESPONSE';
export const FETCH_QUESTIONS_WITH_TYPE_ERROR = 'FETCH_QUESTIONS_WITH_TYPE_ERROR';

export const SHOW_QUESTION_FORM = 'SHOW_QUESTION_FORM';
export const HIDE_QUESTION_FORM = 'HIDE_QUESTION_FORM';

export const ADD_QUESTION_RESPONSE = 'ADD_QUESTION_RESPONSE';
export const REMOVE_QUESTION_RESPONSE = 'REMOVE_QUESTION_RESPONSE';
export const IMPORT_QUESTIONS_RESPONSE = 'IMPORT_QUESTIONS_RESPONSE';
export const SEARCH_QUESTIONS_RESPONSE = 'SEARCH_QUESTIONS_RESPONSE';

export const ADD_QUESTION_TYPE_RESPONSE = 'ADD_QUESTION_TYPE_RESPONSE';
export const REMOVE_QUESTION_TYPE_RESPONSE = 'REMOVE_QUESTION_TYPE_RESPONSE';
export const FETCH_ALL_QUESTION_TYPE_RESPONSE = 'FETCH_ALL_QUESTION_TYPE_RESPONSE';
export const UPDATE_SELECTED_QUESTIONS = 'UPDATE_SELECTED_QUESTIONS';
export const CONFIRM_SELECTED = 'CONFIRM_SELECTED';
export const MARK_AS_CORRECT_OPTION = 'MARK_AS_CORRECT_OPTION';

export const FETCH_SAVED_QUESTIONS  = 'FETCH_SAVED_QUESTIONS';
export const FETCH_ANSWER_KEYS  = 'FETCH_ANSWER_KEYS';
export const REMOVE_SAVED_QUESTION_SECTION  = 'REMOVE_SAVED_QUESTION_SECTION';
export const SAVE_PAPER_RESPONSE = 'SAVE_PAPER_RESPONSE';
export const TOGGLE_PAPER_SETTING = 'TOGGLE_PAPER_SETTING';
export const UPDATE_PAPER_SETTING = 'UPDATE_PAPER_SETTING';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const EDIT_QUESTION_SECTION = 'EDIT_QUESTION_SECTION';
