export const REQUEST_INIT = 'REQUEST_INIT';
export const FETCH_DATA_SECTIONS_RESPONSE = 'FETCH_DATA_SECTIONS_RESPONSE';
export const FETCH_SUBJECT_RESPONSE = 'FETCH_SUBJECT_RESPONSE';

export const ADD_SECTION_RESPONSE = 'ADD_SECTION_RESPONSE';
export const REMOVE_SECTION_RESPONSE = 'REMOVE_SECTION_RESPONSE';

export const ADD_TOPIC_RESPONSE = 'ADD_TOPIC_RESPONSE';
export const REMOVE_TOPIC_RESPONSE = 'REMOVE_TOPIC_RESPONSE';

export const SHOW_TOPIC_FORM = 'SHOW_TOPIC_FORM';
export const HIDE_TOPIC_FORM = 'HIDE_TOPIC_FORM';

export const PROCESS_IMPORT_RESPONSE = 'PROCESS_IMPORT_RESPONSE';
export const IMPORTED_TOPICS_RESPONSE = 'IMPORTED_TOPICS_RESPONSE';
export const SELECTED_SECTION_RESPONSE = 'SELECTED_SECTION_RESPONSE';
