export const REQUEST_INIT = 'REQUEST_INIT';
export const FETCH_DATA_CLASSES_RESPONSE = 'FETCH_DATA_CLASSES_RESPONSE';
export const FETCH_ALL_CLASSES_RESPONSE = 'FETCH_ALL_CLASSES_RESPONSE';
export const FETCH_ALL_PUBLISHERS = 'FETCH_ALL_PUBLISHERS';
export const ADD_CLASS_RESPONSE = 'ADD_CLASS_RESPONSE';
export const REMOVE_CLASS_RESPONSE = 'REMOVE_CLASS_RESPONSE';
export const FETCH_CLASS_BY_ID = 'FETCH_CLASS_BY_ID';
