export const REQUEST_INIT = 'REQUEST_INIT';
export const FETCH_CLASSES_RESPONSE = 'FETCH_CLASSES_RESPONSE';
export const FETCH_SUBJECTS_RESPONSE = 'FETCH_SUBJECTS_RESPONSE';
export const UPLOAD_FILES_RESPONSE = 'UPLOAD_FILES_RESPONSE';
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';
